<?php

/**
 * Basedireccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_direccion
 * @property string $pais
 * @property string $estado
 * @property string $ciudad
 * @property string $municipio
 * @property string $delegacion
 * @property string $direccion
 * @property string $referencia
 * @property string $numero
 * @property string $cp
 * @property integer $id_unidad
 * @property integer $id_empresa
 * 
 * @method integer   getIdDireccion()  Returns the current record's "id_direccion" value
 * @method string    getPais()         Returns the current record's "pais" value
 * @method string    getEstado()       Returns the current record's "estado" value
 * @method string    getCiudad()       Returns the current record's "ciudad" value
 * @method string    getMunicipio()    Returns the current record's "municipio" value
 * @method string    getDelegacion()   Returns the current record's "delegacion" value
 * @method string    getDireccion()    Returns the current record's "direccion" value
 * @method string    getReferencia()   Returns the current record's "referencia" value
 * @method string    getNumero()       Returns the current record's "numero" value
 * @method string    getCp()           Returns the current record's "cp" value
 * @method integer   getIdUnidad()     Returns the current record's "id_unidad" value
 * @method integer   getIdEmpresa()    Returns the current record's "id_empresa" value
 * @method direccion setIdDireccion()  Sets the current record's "id_direccion" value
 * @method direccion setPais()         Sets the current record's "pais" value
 * @method direccion setEstado()       Sets the current record's "estado" value
 * @method direccion setCiudad()       Sets the current record's "ciudad" value
 * @method direccion setMunicipio()    Sets the current record's "municipio" value
 * @method direccion setDelegacion()   Sets the current record's "delegacion" value
 * @method direccion setDireccion()    Sets the current record's "direccion" value
 * @method direccion setReferencia()   Sets the current record's "referencia" value
 * @method direccion setNumero()       Sets the current record's "numero" value
 * @method direccion setCp()           Sets the current record's "cp" value
 * @method direccion setIdUnidad()     Sets the current record's "id_unidad" value
 * @method direccion setIdEmpresa()    Sets the current record's "id_empresa" value
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basedireccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('direccion');
        $this->hasColumn('id_direccion', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('pais', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('estado', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('ciudad', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('municipio', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('delegacion', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('referencia', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('numero', 'string', 11, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('cp', 'string', 11, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_unidad', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_empresa', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}