<?php

/**
 * Baseseccion9
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ps
 * @property integer $id_programa
 * @property integer $id_seccion
 * @property integer $id_usuario_creo
 * @property string $anio1
 * @property string $anio2
 * @property string $anio3
 * @property string $anio4
 * @property string $anio5
 * @property string $indicador
 * @property string $ind_a1a
 * @property string $ind_a2a
 * @property string $ind_a3a
 * @property string $ind_a4a
 * @property string $ind_a5a
 * @property string $indicador2
 * @property string $ind_a1b
 * @property string $ind_a2b
 * @property string $ind_a3b
 * @property string $ind_a4b
 * @property string $ind_a5b
 * @property string $indicador3
 * @property string $ind_a1c
 * @property string $ind_a2c
 * @property string $ind_a3c
 * @property string $ind_a4c
 * @property string $ind_a5c
 * @property string $indicador4
 * @property string $ind_a1d
 * @property string $ind_a2d
 * @property string $ind_a3d
 * @property string $ind_a4d
 * @property string $ind_a5d
 * @property date $creado
 * @property programa $Programa
 * 
 * @method integer  getIdPs()            Returns the current record's "id_ps" value
 * @method integer  getIdPrograma()      Returns the current record's "id_programa" value
 * @method integer  getIdSeccion()       Returns the current record's "id_seccion" value
 * @method integer  getIdUsuarioCreo()   Returns the current record's "id_usuario_creo" value
 * @method string   getAnio1()           Returns the current record's "anio1" value
 * @method string   getAnio2()           Returns the current record's "anio2" value
 * @method string   getAnio3()           Returns the current record's "anio3" value
 * @method string   getAnio4()           Returns the current record's "anio4" value
 * @method string   getAnio5()           Returns the current record's "anio5" value
 * @method string   getIndicador()       Returns the current record's "indicador" value
 * @method string   getIndA1a()          Returns the current record's "ind_a1a" value
 * @method string   getIndA2a()          Returns the current record's "ind_a2a" value
 * @method string   getIndA3a()          Returns the current record's "ind_a3a" value
 * @method string   getIndA4a()          Returns the current record's "ind_a4a" value
 * @method string   getIndA5a()          Returns the current record's "ind_a5a" value
 * @method string   getIndicador2()      Returns the current record's "indicador2" value
 * @method string   getIndA1b()          Returns the current record's "ind_a1b" value
 * @method string   getIndA2b()          Returns the current record's "ind_a2b" value
 * @method string   getIndA3b()          Returns the current record's "ind_a3b" value
 * @method string   getIndA4b()          Returns the current record's "ind_a4b" value
 * @method string   getIndA5b()          Returns the current record's "ind_a5b" value
 * @method string   getIndicador3()      Returns the current record's "indicador3" value
 * @method string   getIndA1c()          Returns the current record's "ind_a1c" value
 * @method string   getIndA2c()          Returns the current record's "ind_a2c" value
 * @method string   getIndA3c()          Returns the current record's "ind_a3c" value
 * @method string   getIndA4c()          Returns the current record's "ind_a4c" value
 * @method string   getIndA5c()          Returns the current record's "ind_a5c" value
 * @method string   getIndicador4()      Returns the current record's "indicador4" value
 * @method string   getIndA1d()          Returns the current record's "ind_a1d" value
 * @method string   getIndA2d()          Returns the current record's "ind_a2d" value
 * @method string   getIndA3d()          Returns the current record's "ind_a3d" value
 * @method string   getIndA4d()          Returns the current record's "ind_a4d" value
 * @method string   getIndA5d()          Returns the current record's "ind_a5d" value
 * @method date     getCreado()          Returns the current record's "creado" value
 * @method programa getPrograma()        Returns the current record's "Programa" value
 * @method seccion9 setIdPs()            Sets the current record's "id_ps" value
 * @method seccion9 setIdPrograma()      Sets the current record's "id_programa" value
 * @method seccion9 setIdSeccion()       Sets the current record's "id_seccion" value
 * @method seccion9 setIdUsuarioCreo()   Sets the current record's "id_usuario_creo" value
 * @method seccion9 setAnio1()           Sets the current record's "anio1" value
 * @method seccion9 setAnio2()           Sets the current record's "anio2" value
 * @method seccion9 setAnio3()           Sets the current record's "anio3" value
 * @method seccion9 setAnio4()           Sets the current record's "anio4" value
 * @method seccion9 setAnio5()           Sets the current record's "anio5" value
 * @method seccion9 setIndicador()       Sets the current record's "indicador" value
 * @method seccion9 setIndA1a()          Sets the current record's "ind_a1a" value
 * @method seccion9 setIndA2a()          Sets the current record's "ind_a2a" value
 * @method seccion9 setIndA3a()          Sets the current record's "ind_a3a" value
 * @method seccion9 setIndA4a()          Sets the current record's "ind_a4a" value
 * @method seccion9 setIndA5a()          Sets the current record's "ind_a5a" value
 * @method seccion9 setIndicador2()      Sets the current record's "indicador2" value
 * @method seccion9 setIndA1b()          Sets the current record's "ind_a1b" value
 * @method seccion9 setIndA2b()          Sets the current record's "ind_a2b" value
 * @method seccion9 setIndA3b()          Sets the current record's "ind_a3b" value
 * @method seccion9 setIndA4b()          Sets the current record's "ind_a4b" value
 * @method seccion9 setIndA5b()          Sets the current record's "ind_a5b" value
 * @method seccion9 setIndicador3()      Sets the current record's "indicador3" value
 * @method seccion9 setIndA1c()          Sets the current record's "ind_a1c" value
 * @method seccion9 setIndA2c()          Sets the current record's "ind_a2c" value
 * @method seccion9 setIndA3c()          Sets the current record's "ind_a3c" value
 * @method seccion9 setIndA4c()          Sets the current record's "ind_a4c" value
 * @method seccion9 setIndA5c()          Sets the current record's "ind_a5c" value
 * @method seccion9 setIndicador4()      Sets the current record's "indicador4" value
 * @method seccion9 setIndA1d()          Sets the current record's "ind_a1d" value
 * @method seccion9 setIndA2d()          Sets the current record's "ind_a2d" value
 * @method seccion9 setIndA3d()          Sets the current record's "ind_a3d" value
 * @method seccion9 setIndA4d()          Sets the current record's "ind_a4d" value
 * @method seccion9 setIndA5d()          Sets the current record's "ind_a5d" value
 * @method seccion9 setCreado()          Sets the current record's "creado" value
 * @method seccion9 setPrograma()        Sets the current record's "Programa" value
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseseccion9 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seccion9');
        $this->hasColumn('id_ps', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_programa', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_seccion', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_usuario_creo', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('anio1', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('anio2', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('anio3', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('anio4', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('anio5', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('indicador', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ind_a1a', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a2a', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a3a', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a4a', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a5a', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('indicador2', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ind_a1b', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a2b', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a3b', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a4b', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a5b', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('indicador3', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ind_a1c', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a2c', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a3c', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a4c', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a5c', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('indicador4', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ind_a1d', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a2d', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a3d', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a4d', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('ind_a5d', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('creado', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('programa as Programa', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa',
             'onDelete' => 'CASCADE'));
    }
}