<?php

/**
 * Baseregion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_region
 * @property string $nombre
 * @property Doctrine_Collection $Unidad
 * 
 * @method integer             getIdRegion()  Returns the current record's "id_region" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method Doctrine_Collection getUnidad()    Returns the current record's "Unidad" collection
 * @method region              setIdRegion()  Sets the current record's "id_region" value
 * @method region              setNombre()    Sets the current record's "nombre" value
 * @method region              setUnidad()    Sets the current record's "Unidad" collection
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseregion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('id_region', 'integer', 4, array(
             'unique' => true,
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('unidad as Unidad', array(
             'local' => 'id_region',
             'foreign' => 'id_region'));
    }
}