<?php

/**
 * Baseseccion6
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ps
 * @property integer $id_programa
 * @property integer $id_seccion
 * @property string $tablero
 * @property string $circular
 * @property string $correo
 * @property string $informe
 * @property string $informal
 * @property string $otro_medio
 * @property string $text_otro
 * @property date $creado
 * @property programa $Programa
 * 
 * @method integer  getIdPs()        Returns the current record's "id_ps" value
 * @method integer  getIdPrograma()  Returns the current record's "id_programa" value
 * @method integer  getIdSeccion()   Returns the current record's "id_seccion" value
 * @method string   getTablero()     Returns the current record's "tablero" value
 * @method string   getCircular()    Returns the current record's "circular" value
 * @method string   getCorreo()      Returns the current record's "correo" value
 * @method string   getInforme()     Returns the current record's "informe" value
 * @method string   getInformal()    Returns the current record's "informal" value
 * @method string   getOtroMedio()   Returns the current record's "otro_medio" value
 * @method string   getTextOtro()    Returns the current record's "text_otro" value
 * @method date     getCreado()      Returns the current record's "creado" value
 * @method programa getPrograma()    Returns the current record's "Programa" value
 * @method seccion6 setIdPs()        Sets the current record's "id_ps" value
 * @method seccion6 setIdPrograma()  Sets the current record's "id_programa" value
 * @method seccion6 setIdSeccion()   Sets the current record's "id_seccion" value
 * @method seccion6 setTablero()     Sets the current record's "tablero" value
 * @method seccion6 setCircular()    Sets the current record's "circular" value
 * @method seccion6 setCorreo()      Sets the current record's "correo" value
 * @method seccion6 setInforme()     Sets the current record's "informe" value
 * @method seccion6 setInformal()    Sets the current record's "informal" value
 * @method seccion6 setOtroMedio()   Sets the current record's "otro_medio" value
 * @method seccion6 setTextOtro()    Sets the current record's "text_otro" value
 * @method seccion6 setCreado()      Sets the current record's "creado" value
 * @method seccion6 setPrograma()    Sets the current record's "Programa" value
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseseccion6 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seccion6');
        $this->hasColumn('id_ps', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_programa', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_seccion', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('tablero', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('circular', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('correo', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('informe', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('informal', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('otro_medio', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('text_otro', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('creado', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('programa as Programa', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa',
             'onDelete' => 'CASCADE'));
    }
}