<?php

/**
 * Baseprograma_seccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ps
 * @property integer $id_programa
 * @property integer $id_seccion
 * @property integer $id_usuario_creo
 * @property string $text_content
 * @property string $comentario_consultor
 * @property integer $revision
 * @property integer $activo
 * @property timestamp $creado
 * @property timestamp $actualizado
 * @property programa $programa
 * 
 * @method integer          getIdPs()                 Returns the current record's "id_ps" value
 * @method integer          getIdPrograma()           Returns the current record's "id_programa" value
 * @method integer          getIdSeccion()            Returns the current record's "id_seccion" value
 * @method integer          getIdUsuarioCreo()        Returns the current record's "id_usuario_creo" value
 * @method string           getTextContent()          Returns the current record's "text_content" value
 * @method string           getComentarioConsultor()  Returns the current record's "comentario_consultor" value
 * @method integer          getRevision()             Returns the current record's "revision" value
 * @method integer          getActivo()               Returns the current record's "activo" value
 * @method timestamp        getCreado()               Returns the current record's "creado" value
 * @method timestamp        getActualizado()          Returns the current record's "actualizado" value
 * @method programa         getPrograma()             Returns the current record's "programa" value
 * @method programa_seccion setIdPs()                 Sets the current record's "id_ps" value
 * @method programa_seccion setIdPrograma()           Sets the current record's "id_programa" value
 * @method programa_seccion setIdSeccion()            Sets the current record's "id_seccion" value
 * @method programa_seccion setIdUsuarioCreo()        Sets the current record's "id_usuario_creo" value
 * @method programa_seccion setTextContent()          Sets the current record's "text_content" value
 * @method programa_seccion setComentarioConsultor()  Sets the current record's "comentario_consultor" value
 * @method programa_seccion setRevision()             Sets the current record's "revision" value
 * @method programa_seccion setActivo()               Sets the current record's "activo" value
 * @method programa_seccion setCreado()               Sets the current record's "creado" value
 * @method programa_seccion setActualizado()          Sets the current record's "actualizado" value
 * @method programa_seccion setPrograma()             Sets the current record's "programa" value
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseprograma_seccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('programa_seccion');
        $this->hasColumn('id_ps', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_programa', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_seccion', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_usuario_creo', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('text_content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('comentario_consultor', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('revision', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('activo', 'integer', 1, array(
             'default' => '1',
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('creado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('actualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('programa', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'alias' => 'creado',
              'disabled' => false,
              'name' => 'creado',
             ),
             'updated' => 
             array(
              'alias' => 'actualizado',
              'disabled' => false,
              'name' => 'actualizado',
             ),
             ));
        $this->actAs($timestampable0);
    }
}