<?php

/**
 * Basecomite_usuarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_usuario
 * @property integer $id_comite
 * @property string $cargo_comite
 * @property date $fecha_agregado
 * 
 * @method integer         getIdUsuario()      Returns the current record's "id_usuario" value
 * @method integer         getIdComite()       Returns the current record's "id_comite" value
 * @method string          getCargoComite()    Returns the current record's "cargo_comite" value
 * @method date            getFechaAgregado()  Returns the current record's "fecha_agregado" value
 * @method comite_usuarios setIdUsuario()      Sets the current record's "id_usuario" value
 * @method comite_usuarios setIdComite()       Sets the current record's "id_comite" value
 * @method comite_usuarios setCargoComite()    Sets the current record's "cargo_comite" value
 * @method comite_usuarios setFechaAgregado()  Sets the current record's "fecha_agregado" value
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecomite_usuarios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comite_usuarios');
        $this->hasColumn('id_usuario', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_comite', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('cargo_comite', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('fecha_agregado', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'disabled' => false,
              'alias' => 'fecha_agregado',
             ),
             'updated' => 
             array(
              'disabled' => false,
             ),
             ));
        $this->actAs($timestampable0);
    }
}