<?php

/**
 * Baseseccion8
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ps
 * @property integer $id_seccion
 * @property integer $id_programa
 * @property integer $id_usuario_creo
 * @property integer $p_d
 * @property string $t_p_d
 * @property integer $p_a
 * @property string $t_p_a
 * @property integer $p_c
 * @property string $t_p_c
 * @property integer $p_p
 * @property string $t_p_p
 * @property integer $p_o
 * @property string $t_p_o
 * @property integer $d_d
 * @property string $t_d_d
 * @property integer $d_a
 * @property string $t_d_a
 * @property integer $d_c
 * @property string $t_d_c
 * @property integer $d_p
 * @property string $t_d_p
 * @property integer $d_o
 * @property string $t_d_o
 * @property integer $e_d
 * @property string $t_e_d
 * @property integer $e_a
 * @property string $t_e_a
 * @property integer $e_c
 * @property string $t_e_c
 * @property integer $e_p
 * @property string $t_e_p
 * @property integer $e_o
 * @property string $t_e_o
 * @property integer $r_d
 * @property string $t_r_d
 * @property integer $r_a
 * @property string $t_r_a
 * @property integer $r_c
 * @property string $t_r_c
 * @property integer $r_p
 * @property string $t_r_p
 * @property integer $r_o
 * @property string $t_r_o
 * @property date $fecha_creado
 * @property integer $porcentaje
 * @property programa $Programa
 * 
 * @method integer  getIdPs()            Returns the current record's "id_ps" value
 * @method integer  getIdSeccion()       Returns the current record's "id_seccion" value
 * @method integer  getIdPrograma()      Returns the current record's "id_programa" value
 * @method integer  getIdUsuarioCreo()   Returns the current record's "id_usuario_creo" value
 * @method integer  getPD()              Returns the current record's "p_d" value
 * @method string   getTPD()             Returns the current record's "t_p_d" value
 * @method integer  getPA()              Returns the current record's "p_a" value
 * @method string   getTPA()             Returns the current record's "t_p_a" value
 * @method integer  getPC()              Returns the current record's "p_c" value
 * @method string   getTPC()             Returns the current record's "t_p_c" value
 * @method integer  getPP()              Returns the current record's "p_p" value
 * @method string   getTPP()             Returns the current record's "t_p_p" value
 * @method integer  getPO()              Returns the current record's "p_o" value
 * @method string   getTPO()             Returns the current record's "t_p_o" value
 * @method integer  getDD()              Returns the current record's "d_d" value
 * @method string   getTDD()             Returns the current record's "t_d_d" value
 * @method integer  getDA()              Returns the current record's "d_a" value
 * @method string   getTDA()             Returns the current record's "t_d_a" value
 * @method integer  getDC()              Returns the current record's "d_c" value
 * @method string   getTDC()             Returns the current record's "t_d_c" value
 * @method integer  getDP()              Returns the current record's "d_p" value
 * @method string   getTDP()             Returns the current record's "t_d_p" value
 * @method integer  getDO()              Returns the current record's "d_o" value
 * @method string   getTDO()             Returns the current record's "t_d_o" value
 * @method integer  getED()              Returns the current record's "e_d" value
 * @method string   getTED()             Returns the current record's "t_e_d" value
 * @method integer  getEA()              Returns the current record's "e_a" value
 * @method string   getTEA()             Returns the current record's "t_e_a" value
 * @method integer  getEC()              Returns the current record's "e_c" value
 * @method string   getTEC()             Returns the current record's "t_e_c" value
 * @method integer  getEP()              Returns the current record's "e_p" value
 * @method string   getTEP()             Returns the current record's "t_e_p" value
 * @method integer  getEO()              Returns the current record's "e_o" value
 * @method string   getTEO()             Returns the current record's "t_e_o" value
 * @method integer  getRD()              Returns the current record's "r_d" value
 * @method string   getTRD()             Returns the current record's "t_r_d" value
 * @method integer  getRA()              Returns the current record's "r_a" value
 * @method string   getTRA()             Returns the current record's "t_r_a" value
 * @method integer  getRC()              Returns the current record's "r_c" value
 * @method string   getTRC()             Returns the current record's "t_r_c" value
 * @method integer  getRP()              Returns the current record's "r_p" value
 * @method string   getTRP()             Returns the current record's "t_r_p" value
 * @method integer  getRO()              Returns the current record's "r_o" value
 * @method string   getTRO()             Returns the current record's "t_r_o" value
 * @method date     getFechaCreado()     Returns the current record's "fecha_creado" value
 * @method integer  getPorcentaje()      Returns the current record's "porcentaje" value
 * @method programa getPrograma()        Returns the current record's "Programa" value
 * @method seccion8 setIdPs()            Sets the current record's "id_ps" value
 * @method seccion8 setIdSeccion()       Sets the current record's "id_seccion" value
 * @method seccion8 setIdPrograma()      Sets the current record's "id_programa" value
 * @method seccion8 setIdUsuarioCreo()   Sets the current record's "id_usuario_creo" value
 * @method seccion8 setPD()              Sets the current record's "p_d" value
 * @method seccion8 setTPD()             Sets the current record's "t_p_d" value
 * @method seccion8 setPA()              Sets the current record's "p_a" value
 * @method seccion8 setTPA()             Sets the current record's "t_p_a" value
 * @method seccion8 setPC()              Sets the current record's "p_c" value
 * @method seccion8 setTPC()             Sets the current record's "t_p_c" value
 * @method seccion8 setPP()              Sets the current record's "p_p" value
 * @method seccion8 setTPP()             Sets the current record's "t_p_p" value
 * @method seccion8 setPO()              Sets the current record's "p_o" value
 * @method seccion8 setTPO()             Sets the current record's "t_p_o" value
 * @method seccion8 setDD()              Sets the current record's "d_d" value
 * @method seccion8 setTDD()             Sets the current record's "t_d_d" value
 * @method seccion8 setDA()              Sets the current record's "d_a" value
 * @method seccion8 setTDA()             Sets the current record's "t_d_a" value
 * @method seccion8 setDC()              Sets the current record's "d_c" value
 * @method seccion8 setTDC()             Sets the current record's "t_d_c" value
 * @method seccion8 setDP()              Sets the current record's "d_p" value
 * @method seccion8 setTDP()             Sets the current record's "t_d_p" value
 * @method seccion8 setDO()              Sets the current record's "d_o" value
 * @method seccion8 setTDO()             Sets the current record's "t_d_o" value
 * @method seccion8 setED()              Sets the current record's "e_d" value
 * @method seccion8 setTED()             Sets the current record's "t_e_d" value
 * @method seccion8 setEA()              Sets the current record's "e_a" value
 * @method seccion8 setTEA()             Sets the current record's "t_e_a" value
 * @method seccion8 setEC()              Sets the current record's "e_c" value
 * @method seccion8 setTEC()             Sets the current record's "t_e_c" value
 * @method seccion8 setEP()              Sets the current record's "e_p" value
 * @method seccion8 setTEP()             Sets the current record's "t_e_p" value
 * @method seccion8 setEO()              Sets the current record's "e_o" value
 * @method seccion8 setTEO()             Sets the current record's "t_e_o" value
 * @method seccion8 setRD()              Sets the current record's "r_d" value
 * @method seccion8 setTRD()             Sets the current record's "t_r_d" value
 * @method seccion8 setRA()              Sets the current record's "r_a" value
 * @method seccion8 setTRA()             Sets the current record's "t_r_a" value
 * @method seccion8 setRC()              Sets the current record's "r_c" value
 * @method seccion8 setTRC()             Sets the current record's "t_r_c" value
 * @method seccion8 setRP()              Sets the current record's "r_p" value
 * @method seccion8 setTRP()             Sets the current record's "t_r_p" value
 * @method seccion8 setRO()              Sets the current record's "r_o" value
 * @method seccion8 setTRO()             Sets the current record's "t_r_o" value
 * @method seccion8 setFechaCreado()     Sets the current record's "fecha_creado" value
 * @method seccion8 setPorcentaje()      Sets the current record's "porcentaje" value
 * @method seccion8 setPrograma()        Sets the current record's "Programa" value
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseseccion8 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seccion8');
        $this->hasColumn('id_ps', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_seccion', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_programa', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_usuario_creo', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('p_d', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_p_d', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('p_a', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_p_a', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('p_c', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_p_c', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('p_p', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_p_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('p_o', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_p_o', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('d_d', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_d_d', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('d_a', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_d_a', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('d_c', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_d_c', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('d_p', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_d_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('d_o', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_d_o', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('e_d', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_e_d', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('e_a', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_e_a', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('e_c', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_e_c', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('e_p', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_e_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('e_o', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_e_o', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('r_d', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_r_d', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('r_a', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_r_a', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('r_c', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_r_c', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('r_p', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_r_p', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('r_o', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('t_r_o', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('fecha_creado', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('porcentaje', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));


        $this->index('id_ps', array(
             'fields' => 
             array(
              0 => 'id_ps',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('programa as Programa', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa',
             'onDelete' => 'CASCADE'));
    }
}