<?php

/**
 * Baseprograma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_programa
 * @property integer $id_requisito
 * @property integer $id_comite
 * @property string $nombre
 * @property string $coordinador
 * @property decimal $existencia
 * @property decimal $difusion
 * @property decimal $participacion
 * @property decimal $mejora
 * @property decimal $vinculacion
 * @property decimal $calificacion
 * @property date $fecha_elaboracion
 * @property string $revisor1
 * @property date $fecha_revision
 * @property string $revisor2
 * @property date $fecha_revision2
 * @property string $revisor3
 * @property date $fecha_revision3
 * @property string $revisor4
 * @property date $fecha_revision4
 * @property string $revisor5
 * @property date $fecha_revision5
 * @property integer $id_usuario_elaboro
 * @property integer $id_consultor
 * @property date $fecha_compromiso
 * @property integer $no_revision
 * @property integer $id_usuario_reviso
 * @property integer $id_usuario_modifico
 * @property date $fecha_modifico
 * @property timestamp $creado
 * @property timestamp $actualizado
 * @property string $comentario
 * @property requisito $requisito
 * @property comite $comite
 * @property Doctrine_Collection $programa_anexos
 * @property Doctrine_Collection $programa_seccion
 * @property Doctrine_Collection $Seccion10
 * @property Doctrine_Collection $Seccion5
 * @property Doctrine_Collection $Seccion6
 * @property Doctrine_Collection $Seccion8
 * @property Doctrine_Collection $Seccion9
 * 
 * @method integer             getIdPrograma()          Returns the current record's "id_programa" value
 * @method integer             getIdRequisito()         Returns the current record's "id_requisito" value
 * @method integer             getIdComite()            Returns the current record's "id_comite" value
 * @method string              getNombre()              Returns the current record's "nombre" value
 * @method string              getCoordinador()         Returns the current record's "coordinador" value
 * @method decimal             getExistencia()          Returns the current record's "existencia" value
 * @method decimal             getDifusion()            Returns the current record's "difusion" value
 * @method decimal             getParticipacion()       Returns the current record's "participacion" value
 * @method decimal             getMejora()              Returns the current record's "mejora" value
 * @method decimal             getVinculacion()         Returns the current record's "vinculacion" value
 * @method decimal             getCalificacion()        Returns the current record's "calificacion" value
 * @method date                getFechaElaboracion()    Returns the current record's "fecha_elaboracion" value
 * @method string              getRevisor1()            Returns the current record's "revisor1" value
 * @method date                getFechaRevision()       Returns the current record's "fecha_revision" value
 * @method string              getRevisor2()            Returns the current record's "revisor2" value
 * @method date                getFechaRevision2()      Returns the current record's "fecha_revision2" value
 * @method string              getRevisor3()            Returns the current record's "revisor3" value
 * @method date                getFechaRevision3()      Returns the current record's "fecha_revision3" value
 * @method string              getRevisor4()            Returns the current record's "revisor4" value
 * @method date                getFechaRevision4()      Returns the current record's "fecha_revision4" value
 * @method string              getRevisor5()            Returns the current record's "revisor5" value
 * @method date                getFechaRevision5()      Returns the current record's "fecha_revision5" value
 * @method integer             getIdUsuarioElaboro()    Returns the current record's "id_usuario_elaboro" value
 * @method integer             getIdConsultor()         Returns the current record's "id_consultor" value
 * @method date                getFechaCompromiso()     Returns the current record's "fecha_compromiso" value
 * @method integer             getNoRevision()          Returns the current record's "no_revision" value
 * @method integer             getIdUsuarioReviso()     Returns the current record's "id_usuario_reviso" value
 * @method integer             getIdUsuarioModifico()   Returns the current record's "id_usuario_modifico" value
 * @method date                getFechaModifico()       Returns the current record's "fecha_modifico" value
 * @method timestamp           getCreado()              Returns the current record's "creado" value
 * @method timestamp           getActualizado()         Returns the current record's "actualizado" value
 * @method string              getComentario()          Returns the current record's "comentario" value
 * @method requisito           getRequisito()           Returns the current record's "requisito" value
 * @method comite              getComite()              Returns the current record's "comite" value
 * @method Doctrine_Collection getProgramaAnexos()      Returns the current record's "programa_anexos" collection
 * @method Doctrine_Collection getProgramaSeccion()     Returns the current record's "programa_seccion" collection
 * @method Doctrine_Collection getSeccion10()           Returns the current record's "Seccion10" collection
 * @method Doctrine_Collection getSeccion5()            Returns the current record's "Seccion5" collection
 * @method Doctrine_Collection getSeccion6()            Returns the current record's "Seccion6" collection
 * @method Doctrine_Collection getSeccion8()            Returns the current record's "Seccion8" collection
 * @method Doctrine_Collection getSeccion9()            Returns the current record's "Seccion9" collection
 * @method programa            setIdPrograma()          Sets the current record's "id_programa" value
 * @method programa            setIdRequisito()         Sets the current record's "id_requisito" value
 * @method programa            setIdComite()            Sets the current record's "id_comite" value
 * @method programa            setNombre()              Sets the current record's "nombre" value
 * @method programa            setCoordinador()         Sets the current record's "coordinador" value
 * @method programa            setExistencia()          Sets the current record's "existencia" value
 * @method programa            setDifusion()            Sets the current record's "difusion" value
 * @method programa            setParticipacion()       Sets the current record's "participacion" value
 * @method programa            setMejora()              Sets the current record's "mejora" value
 * @method programa            setVinculacion()         Sets the current record's "vinculacion" value
 * @method programa            setCalificacion()        Sets the current record's "calificacion" value
 * @method programa            setFechaElaboracion()    Sets the current record's "fecha_elaboracion" value
 * @method programa            setRevisor1()            Sets the current record's "revisor1" value
 * @method programa            setFechaRevision()       Sets the current record's "fecha_revision" value
 * @method programa            setRevisor2()            Sets the current record's "revisor2" value
 * @method programa            setFechaRevision2()      Sets the current record's "fecha_revision2" value
 * @method programa            setRevisor3()            Sets the current record's "revisor3" value
 * @method programa            setFechaRevision3()      Sets the current record's "fecha_revision3" value
 * @method programa            setRevisor4()            Sets the current record's "revisor4" value
 * @method programa            setFechaRevision4()      Sets the current record's "fecha_revision4" value
 * @method programa            setRevisor5()            Sets the current record's "revisor5" value
 * @method programa            setFechaRevision5()      Sets the current record's "fecha_revision5" value
 * @method programa            setIdUsuarioElaboro()    Sets the current record's "id_usuario_elaboro" value
 * @method programa            setIdConsultor()         Sets the current record's "id_consultor" value
 * @method programa            setFechaCompromiso()     Sets the current record's "fecha_compromiso" value
 * @method programa            setNoRevision()          Sets the current record's "no_revision" value
 * @method programa            setIdUsuarioReviso()     Sets the current record's "id_usuario_reviso" value
 * @method programa            setIdUsuarioModifico()   Sets the current record's "id_usuario_modifico" value
 * @method programa            setFechaModifico()       Sets the current record's "fecha_modifico" value
 * @method programa            setCreado()              Sets the current record's "creado" value
 * @method programa            setActualizado()         Sets the current record's "actualizado" value
 * @method programa            setComentario()          Sets the current record's "comentario" value
 * @method programa            setRequisito()           Sets the current record's "requisito" value
 * @method programa            setComite()              Sets the current record's "comite" value
 * @method programa            setProgramaAnexos()      Sets the current record's "programa_anexos" collection
 * @method programa            setProgramaSeccion()     Sets the current record's "programa_seccion" collection
 * @method programa            setSeccion10()           Sets the current record's "Seccion10" collection
 * @method programa            setSeccion5()            Sets the current record's "Seccion5" collection
 * @method programa            setSeccion6()            Sets the current record's "Seccion6" collection
 * @method programa            setSeccion8()            Sets the current record's "Seccion8" collection
 * @method programa            setSeccion9()            Sets the current record's "Seccion9" collection
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseprograma extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('programa');
        $this->hasColumn('id_programa', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_requisito', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_comite', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('coordinador', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('existencia', 'decimal', 3, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 3,
             ));
        $this->hasColumn('difusion', 'decimal', 3, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 3,
             ));
        $this->hasColumn('participacion', 'decimal', 3, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 3,
             ));
        $this->hasColumn('mejora', 'decimal', 3, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 3,
             ));
        $this->hasColumn('vinculacion', 'decimal', 3, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 3,
             ));
        $this->hasColumn('calificacion', 'decimal', 3, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 3,
             ));
        $this->hasColumn('fecha_elaboracion', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('revisor1', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('fecha_revision', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('revisor2', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('fecha_revision2', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('revisor3', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('fecha_revision3', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('revisor4', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('fecha_revision4', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('revisor5', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('fecha_revision5', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('id_usuario_elaboro', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_consultor', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('fecha_compromiso', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('no_revision', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_usuario_reviso', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_usuario_modifico', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('fecha_modifico', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('creado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('actualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('comentario', 'string', 600, array(
             'type' => 'string',
             'length' => 600,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('requisito', array(
             'local' => 'id_requisito',
             'foreign' => 'id_requisito',
             'onDelete' => 'CASCADE'));

        $this->hasOne('comite', array(
             'local' => 'id_comite',
             'foreign' => 'id_comite',
             'onDelete' => 'CASCADE'));

        $this->hasMany('programa_anexos', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa'));

        $this->hasMany('programa_seccion', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa'));

        $this->hasMany('seccion10 as Seccion10', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa'));

        $this->hasMany('seccion5 as Seccion5', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa'));

        $this->hasMany('seccion6 as Seccion6', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa'));

        $this->hasMany('seccion8 as Seccion8', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa'));

        $this->hasMany('seccion9 as Seccion9', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'alias' => 'creado',
              'disabled' => false,
              'name' => 'creado',
             ),
             'updated' => 
             array(
              'alias' => 'actualizado',
              'name' => 'actualizado',
              'disabled' => false,
             ),
             ));
        $this->actAs($timestampable0);
    }
}