<?php

/**
 * Baseusuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_usuario
 * @property integer $id_empresa
 * @property integer $id_grupo
 * @property integer $id_unidad
 * @property integer $id_comite
 * @property string $foto
 * @property string $nombre
 * @property string $nombre_usuario
 * @property string $primer_apellido
 * @property string $segundo_apellido
 * @property string $email
 * @property string $telefono_fijo
 * @property string $telefono_celular
 * @property string $email_emergencia
 * @property string $cargo
 * @property string $password
 * @property string $salt
 * @property string $palabra_clave
 * @property boolean $activo
 * @property integer $tipo
 * @property timestamp $creado
 * @property timestamp $actualizado
 * @property usuario_grupo $usuario_grupo
 * @property empresa $empresa
 * @property unidad $Unidad
 * @property comite $Comiteusr
 * @property Doctrine_Collection $Comusu
 * @property Doctrine_Collection $Comite
 * @property Doctrine_Collection $unidad
 * @property Doctrine_Collection $unidadConsultor
 * @property Doctrine_Collection $UnidadGte
 * @property Doctrine_Collection $UnidadSubd
 * @property Doctrine_Collection $UnidadDirg
 * 
 * @method integer             getIdUsuario()        Returns the current record's "id_usuario" value
 * @method integer             getIdEmpresa()        Returns the current record's "id_empresa" value
 * @method integer             getIdGrupo()          Returns the current record's "id_grupo" value
 * @method integer             getIdUnidad()         Returns the current record's "id_unidad" value
 * @method integer             getIdComite()         Returns the current record's "id_comite" value
 * @method string              getFoto()             Returns the current record's "foto" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method string              getNombreUsuario()    Returns the current record's "nombre_usuario" value
 * @method string              getPrimerApellido()   Returns the current record's "primer_apellido" value
 * @method string              getSegundoApellido()  Returns the current record's "segundo_apellido" value
 * @method string              getEmail()            Returns the current record's "email" value
 * @method string              getTelefonoFijo()     Returns the current record's "telefono_fijo" value
 * @method string              getTelefonoCelular()  Returns the current record's "telefono_celular" value
 * @method string              getEmailEmergencia()  Returns the current record's "email_emergencia" value
 * @method string              getCargo()            Returns the current record's "cargo" value
 * @method string              getPassword()         Returns the current record's "password" value
 * @method string              getSalt()             Returns the current record's "salt" value
 * @method string              getPalabraClave()     Returns the current record's "palabra_clave" value
 * @method boolean             getActivo()           Returns the current record's "activo" value
 * @method integer             getTipo()             Returns the current record's "tipo" value
 * @method timestamp           getCreado()           Returns the current record's "creado" value
 * @method timestamp           getActualizado()      Returns the current record's "actualizado" value
 * @method usuario_grupo       getUsuarioGrupo()     Returns the current record's "usuario_grupo" value
 * @method empresa             getEmpresa()          Returns the current record's "empresa" value
 * @method unidad              getUnidad()           Returns the current record's "Unidad" value
 * @method comite              getComiteusr()        Returns the current record's "Comiteusr" value
 * @method Doctrine_Collection getComusu()           Returns the current record's "Comusu" collection
 * @method Doctrine_Collection getComite()           Returns the current record's "Comite" collection
 * @method Doctrine_Collection getUnidad()           Returns the current record's "unidad" collection
 * @method Doctrine_Collection getUnidadConsultor()  Returns the current record's "unidadConsultor" collection
 * @method Doctrine_Collection getUnidadGte()        Returns the current record's "UnidadGte" collection
 * @method Doctrine_Collection getUnidadSubd()       Returns the current record's "UnidadSubd" collection
 * @method Doctrine_Collection getUnidadDirg()       Returns the current record's "UnidadDirg" collection
 * @method usuario             setIdUsuario()        Sets the current record's "id_usuario" value
 * @method usuario             setIdEmpresa()        Sets the current record's "id_empresa" value
 * @method usuario             setIdGrupo()          Sets the current record's "id_grupo" value
 * @method usuario             setIdUnidad()         Sets the current record's "id_unidad" value
 * @method usuario             setIdComite()         Sets the current record's "id_comite" value
 * @method usuario             setFoto()             Sets the current record's "foto" value
 * @method usuario             setNombre()           Sets the current record's "nombre" value
 * @method usuario             setNombreUsuario()    Sets the current record's "nombre_usuario" value
 * @method usuario             setPrimerApellido()   Sets the current record's "primer_apellido" value
 * @method usuario             setSegundoApellido()  Sets the current record's "segundo_apellido" value
 * @method usuario             setEmail()            Sets the current record's "email" value
 * @method usuario             setTelefonoFijo()     Sets the current record's "telefono_fijo" value
 * @method usuario             setTelefonoCelular()  Sets the current record's "telefono_celular" value
 * @method usuario             setEmailEmergencia()  Sets the current record's "email_emergencia" value
 * @method usuario             setCargo()            Sets the current record's "cargo" value
 * @method usuario             setPassword()         Sets the current record's "password" value
 * @method usuario             setSalt()             Sets the current record's "salt" value
 * @method usuario             setPalabraClave()     Sets the current record's "palabra_clave" value
 * @method usuario             setActivo()           Sets the current record's "activo" value
 * @method usuario             setTipo()             Sets the current record's "tipo" value
 * @method usuario             setCreado()           Sets the current record's "creado" value
 * @method usuario             setActualizado()      Sets the current record's "actualizado" value
 * @method usuario             setUsuarioGrupo()     Sets the current record's "usuario_grupo" value
 * @method usuario             setEmpresa()          Sets the current record's "empresa" value
 * @method usuario             setUnidad()           Sets the current record's "Unidad" value
 * @method usuario             setComiteusr()        Sets the current record's "Comiteusr" value
 * @method usuario             setComusu()           Sets the current record's "Comusu" collection
 * @method usuario             setComite()           Sets the current record's "Comite" collection
 * @method usuario             setUnidad()           Sets the current record's "unidad" collection
 * @method usuario             setUnidadConsultor()  Sets the current record's "unidadConsultor" collection
 * @method usuario             setUnidadGte()        Sets the current record's "UnidadGte" collection
 * @method usuario             setUnidadSubd()       Sets the current record's "UnidadSubd" collection
 * @method usuario             setUnidadDirg()       Sets the current record's "UnidadDirg" collection
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseusuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id_usuario', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_empresa', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_grupo', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_unidad', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_comite', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('foto', 'string', 300, array(
             'type' => 'string',
             'length' => 300,
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('nombre_usuario', 'string', 64, array(
             'unique' => true,
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('primer_apellido', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('segundo_apellido', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('email', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('telefono_fijo', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('telefono_celular', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('email_emergencia', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('cargo', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('password', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('salt', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('palabra_clave', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'default' => 1,
             'type' => 'boolean',
             ));
        $this->hasColumn('tipo', 'integer', 1, array(
             'default' => 0,
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('creado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('actualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('usuario_grupo', array(
             'local' => 'id_grupo',
             'foreign' => 'id_grupo',
             'onDelete' => 'restrict'));

        $this->hasOne('empresa', array(
             'local' => 'id_empresa',
             'foreign' => 'id_empresa',
             'onDelete' => 'restrict'));

        $this->hasOne('unidad as Unidad', array(
             'local' => 'id_unidad',
             'foreign' => 'id_unidad'));

        $this->hasOne('comite as Comiteusr', array(
             'local' => 'id_comite',
             'foreign' => 'id_comite'));

        $this->hasMany('comite as Comusu', array(
             'refClass' => 'comite_usuarios',
             'local' => 'id_usuario',
             'foreign' => 'id_comite'));

        $this->hasMany('comite as Comite', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario_presidente'));

        $this->hasMany('unidad', array(
             'local' => 'id_usuario',
             'foreign' => 'id_usuario'));

        $this->hasMany('unidad as unidadConsultor', array(
             'local' => 'id_usuario',
             'foreign' => 'id_consultor'));

        $this->hasMany('unidad as UnidadGte', array(
             'local' => 'id_usuario',
             'foreign' => 'id_gerente'));

        $this->hasMany('unidad as UnidadSubd', array(
             'local' => 'id_usuario',
             'foreign' => 'id_subdirector'));

        $this->hasMany('unidad as UnidadDirg', array(
             'local' => 'id_usuario',
             'foreign' => 'id_director_general'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'disabled' => false,
              'alias' => 'creado',
              'name' => 'creado',
             ),
             'updated' => 
             array(
              'alias' => 'actualizado',
              'disabled' => false,
              'name' => 'actualizado',
             ),
             ));
        $this->actAs($timestampable0);
    }
}