<?php

/**
 * Basecertificado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_certificado
 * @property string $nombre
 * @property string $descripcion
 * 
 * @method integer     getIdCertificado()  Returns the current record's "id_certificado" value
 * @method string      getNombre()         Returns the current record's "nombre" value
 * @method string      getDescripcion()    Returns the current record's "descripcion" value
 * @method certificado setIdCertificado()  Sets the current record's "id_certificado" value
 * @method certificado setNombre()         Sets the current record's "nombre" value
 * @method certificado setDescripcion()    Sets the current record's "descripcion" value
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecertificado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('certificado');
        $this->hasColumn('id_certificado', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('descripcion', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}