<?php

/**
 * Baseusuario_grupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_grupo
 * @property string $nombre
 * @property string $permisos
 * @property Doctrine_Collection $usuario
 * 
 * @method integer             getIdGrupo()  Returns the current record's "id_grupo" value
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method string              getPermisos() Returns the current record's "permisos" value
 * @method Doctrine_Collection getUsuario()  Returns the current record's "usuario" collection
 * @method usuario_grupo       setIdGrupo()  Sets the current record's "id_grupo" value
 * @method usuario_grupo       setNombre()   Sets the current record's "nombre" value
 * @method usuario_grupo       setPermisos() Sets the current record's "permisos" value
 * @method usuario_grupo       setUsuario()  Sets the current record's "usuario" collection
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseusuario_grupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_grupo');
        $this->hasColumn('id_grupo', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('nombre', 'string', 64, array(
             'type' => 'string',
             'length' => 64,
             ));
        $this->hasColumn('permisos', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('usuario', array(
             'local' => 'id_grupo',
             'foreign' => 'id_grupo'));
    }
}