<?php

/**
 * Basesemaforo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_semaforo
 * @property integer $id_unidad_negocio
 * @property integer $id_certificado
 * @property integer $id_certificado_proceso
 * @property decimal $calificacion
 * @property integer $horas_acordadas
 * @property integer $tiempo_presencial
 * @property integer $tiempo_virtual
 * @property string $comentarios_gerente
 * @property string $comentarios_resultado
 * @property date $auditoria_interna
 * @property date $auditoria_proxima
 * @property string $url_semaforo
 * @property timestamp $creado
 * @property timestamp $actualizado
 * 
 * @method integer   getIdSemaforo()             Returns the current record's "id_semaforo" value
 * @method integer   getIdUnidadNegocio()        Returns the current record's "id_unidad_negocio" value
 * @method integer   getIdCertificado()          Returns the current record's "id_certificado" value
 * @method integer   getIdCertificadoProceso()   Returns the current record's "id_certificado_proceso" value
 * @method decimal   getCalificacion()           Returns the current record's "calificacion" value
 * @method integer   getHorasAcordadas()         Returns the current record's "horas_acordadas" value
 * @method integer   getTiempoPresencial()       Returns the current record's "tiempo_presencial" value
 * @method integer   getTiempoVirtual()          Returns the current record's "tiempo_virtual" value
 * @method string    getComentariosGerente()     Returns the current record's "comentarios_gerente" value
 * @method string    getComentariosResultado()   Returns the current record's "comentarios_resultado" value
 * @method date      getAuditoriaInterna()       Returns the current record's "auditoria_interna" value
 * @method date      getAuditoriaProxima()       Returns the current record's "auditoria_proxima" value
 * @method string    getUrlSemaforo()            Returns the current record's "url_semaforo" value
 * @method timestamp getCreado()                 Returns the current record's "creado" value
 * @method timestamp getActualizado()            Returns the current record's "actualizado" value
 * @method semaforo  setIdSemaforo()             Sets the current record's "id_semaforo" value
 * @method semaforo  setIdUnidadNegocio()        Sets the current record's "id_unidad_negocio" value
 * @method semaforo  setIdCertificado()          Sets the current record's "id_certificado" value
 * @method semaforo  setIdCertificadoProceso()   Sets the current record's "id_certificado_proceso" value
 * @method semaforo  setCalificacion()           Sets the current record's "calificacion" value
 * @method semaforo  setHorasAcordadas()         Sets the current record's "horas_acordadas" value
 * @method semaforo  setTiempoPresencial()       Sets the current record's "tiempo_presencial" value
 * @method semaforo  setTiempoVirtual()          Sets the current record's "tiempo_virtual" value
 * @method semaforo  setComentariosGerente()     Sets the current record's "comentarios_gerente" value
 * @method semaforo  setComentariosResultado()   Sets the current record's "comentarios_resultado" value
 * @method semaforo  setAuditoriaInterna()       Sets the current record's "auditoria_interna" value
 * @method semaforo  setAuditoriaProxima()       Sets the current record's "auditoria_proxima" value
 * @method semaforo  setUrlSemaforo()            Sets the current record's "url_semaforo" value
 * @method semaforo  setCreado()                 Sets the current record's "creado" value
 * @method semaforo  setActualizado()            Sets the current record's "actualizado" value
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesemaforo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('semaforo');
        $this->hasColumn('id_semaforo', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_unidad_negocio', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_certificado', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_certificado_proceso', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('calificacion', 'decimal', 3, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 3,
             ));
        $this->hasColumn('horas_acordadas', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('tiempo_presencial', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('tiempo_virtual', 'integer', 5, array(
             'type' => 'integer',
             'length' => 5,
             ));
        $this->hasColumn('comentarios_gerente', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('comentarios_resultado', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('auditoria_interna', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('auditoria_proxima', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('url_semaforo', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('creado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('actualizado', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'alias' => 'creado',
              'disabled' => false,
              'name' => 'creado',
             ),
             'updated' => 
             array(
              'alias' => 'actualizado',
              'disabled' => false,
              'name' => 'actualizado',
             ),
             ));
        $this->actAs($timestampable0);
    }
}