<?php

/**
 * Baseseccion5
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_ps
 * @property integer $id_programa
 * @property integer $id_seccion
 * @property string $directivos
 * @property string $personalno_sin
 * @property string $personal_sin
 * @property string $t_personal
 * @property string $f_personal
 * @property string $o_grupos
 * @property string $text_otros
 * @property date $creado
 * @property programa $Programa
 * 
 * @method integer  getIdPs()           Returns the current record's "id_ps" value
 * @method integer  getIdPrograma()     Returns the current record's "id_programa" value
 * @method integer  getIdSeccion()      Returns the current record's "id_seccion" value
 * @method string   getDirectivos()     Returns the current record's "directivos" value
 * @method string   getPersonalnoSin()  Returns the current record's "personalno_sin" value
 * @method string   getPersonalSin()    Returns the current record's "personal_sin" value
 * @method string   getTPersonal()      Returns the current record's "t_personal" value
 * @method string   getFPersonal()      Returns the current record's "f_personal" value
 * @method string   getOGrupos()        Returns the current record's "o_grupos" value
 * @method string   getTextOtros()      Returns the current record's "text_otros" value
 * @method date     getCreado()         Returns the current record's "creado" value
 * @method programa getPrograma()       Returns the current record's "Programa" value
 * @method seccion5 setIdPs()           Sets the current record's "id_ps" value
 * @method seccion5 setIdPrograma()     Sets the current record's "id_programa" value
 * @method seccion5 setIdSeccion()      Sets the current record's "id_seccion" value
 * @method seccion5 setDirectivos()     Sets the current record's "directivos" value
 * @method seccion5 setPersonalnoSin()  Sets the current record's "personalno_sin" value
 * @method seccion5 setPersonalSin()    Sets the current record's "personal_sin" value
 * @method seccion5 setTPersonal()      Sets the current record's "t_personal" value
 * @method seccion5 setFPersonal()      Sets the current record's "f_personal" value
 * @method seccion5 setOGrupos()        Sets the current record's "o_grupos" value
 * @method seccion5 setTextOtros()      Sets the current record's "text_otros" value
 * @method seccion5 setCreado()         Sets the current record's "creado" value
 * @method seccion5 setPrograma()       Sets the current record's "Programa" value
 * 
 * @package    carpetavirtual
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseseccion5 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seccion5');
        $this->hasColumn('id_ps', 'integer', 11, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('id_programa', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('id_seccion', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('directivos', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('personalno_sin', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('personal_sin', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('t_personal', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('f_personal', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('o_grupos', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('text_otros', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('creado', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('programa as Programa', array(
             'local' => 'id_programa',
             'foreign' => 'id_programa',
             'onDelete' => 'CASCADE'));
    }
}